# All service accounts get default restricted access to all namespaces
---
# ClusterRole for applications
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dlab:psp:standard
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - dlab-a-restricted

---
# Mapping any application service accounts and application role together
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dlab:psp:standard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dlab:psp:standard:role
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
 