apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-storage
provisioner: dylanlab.xyz/k8s-storage-provisioner
parameters:
  archiveOnDelete: "false"
  #server: 10.0.55.10
  #path: /mnt/Small/k8s-storage 
  #readOnly: "false"